### ISSUE TITLE
Tachiyomi's icon's strokes are a tad too thin

### ISSUE THREAD

**Issue by ewen-lbh** [mirrorkeydev/Appstract#28]
![Screenshot_20210105-194135.png](https://user-images.githubusercontent.com/39094199/103685821-2171f980-4f8e-11eb-9886-f85c3a374707.png)

I'm self-assigning this issue since I created the icon

EDIT: Welp, can't self assign here. I did it in my head at least

**Comment by mirrorkeydev** [comment]
Sounds good! Also, your home screen looks beautiful!

**Comment by ewen-lbh** [comment]
> Sounds good! Also, your home screen looks beautiful!

Haha thanks! I still need to design icons for wolfram & office lens, they _really_ stick out now that all the others are appstracted :)

**Comment by tausifahmad28** [comment]
> > Sounds good! Also, your home screen looks beautiful!
> 
> Haha thanks! I still need to design icons for wolfram & office lens, they _really_ stick out now that all the others are appstracted :)

Thank you for your work
