### ISSUE TITLE
Support for Oxygen OS launcher?

### ISSUE THREAD

**Issue by andrea-nistico** [mirrorkeydev/Appstract#30]
Is it possible to add support for Oxygen OS launcher? I can't find it on the apply page and I really like it. Thanks!

**Comment by mirrorkeydev** [comment]
You'll want to ask [here](https://github.com/zixpo/candybar), that's the icon pack dashboard that Appstract is built on top of :) Looks like it's [not currently supported](https://github.com/zixpo/candybar/blob/225a94bc6ed2a8985a4aceedff381be6f0c24b94/library/src/main/res/values/dashboard_launchers.xml#L5-L36).

**Comment by andrea-nistico** [comment]
Thanks, I discovered that it is indeed supported. In order to activate the app, the user must go to the appearance settings in OxygenOS, from there the pack is visible.
