### ISSUE TITLE
Playstore and in app version number of Abstract dark icon pack seem to be off

### ISSUE THREAD

**Issue by baschi29** [mirrorkeydev/Appstract#31]
This may be on my side, but it seems that the version Info displayed in the Appstract icon pack (dark theme) app aswell as the version info in the google playstore isn't correct.

I just updated and it's showing me version 3.0.4 while the latest version according to github is 4.0.4

**Comment by mirrorkeydev** [comment]
The dark version of Appstract is one major version behind, because I created it later than the original one :) I.e. I made Appstract Dark 1.0.0 when Appstract Light was already on 2.0.0. I should really fix that sometime though, you're right.
