### ISSUE TITLE
License check failing

### ISSUE THREAD

**Issue by n-marci** [mirrorkeydev/Appstract#43]
When downloading the app from the Aurora Store (alternative to the Play Store), the License Check returns:
'Unable to check license, please try again in a few moments.' every time when opening the app.

Is it possible to make the app available through F-droid or should I try to build it from source?
Thanks a lot for this work of art!

**Comment by n-marci** [comment]
Just saw the closed issue basically noting the same problem, you can close this issue if there are no plans to switch to the fully open source candybar version.

**Comment by mirrorkeydev** [comment]
Please see the note added to the top of the README
