### ISSUE TITLE
White outline option please!

### ISSUE THREAD

**Issue by jonasisozen** [mirrorkeydev/Appstract#46]
Like the title says. I really love this icon pack but it gets hard to see on some dark wallpapers I wanna use. White outline option would make it more readable in my opinion and it shouldn't be so hard to implement. I use lawnchair as my louncher and tryed both versions of Appstract
Thank you in advance

**Comment by mirrorkeydev** [comment]
[Appstract Dark Theme](https://play.google.com/store/apps/details?id=com.melon.appstract.dark&hl=en_US&gl=US) should have what you're looking for.
